#pragma once

#define GPIO_CLOCK_PIN1 19
#define GPIO_CLOCK_PIN2 3
#define GPIO_DATA_PIN1 23
#define GPIO_DATA_PIN2 4

#define TOTAL_NUM_LEDS 220
#define NUM_LEDS_PER_STRAND 220
#define NUM_LEDS_HORIZONTAL 70
#define NUM_LEDS_VERTICAL 40
#define START_LED 170

#define CAM_CAPTURE_FPS 187 
#define CAM_CAPTURE_SIZE_WIDTH 320 
#define CAM_CAPTURE_SIZE_HEIGHT 240 
